import logging
from configparser import ConfigParser
from logging import Logger

DUMMY: str = "<YourNameHere>"

def get_config(log: logging.Logger, config_file: str) -> ConfigParser: ...
def get_default_ini_path() -> str: ...
def make_config(config_file: str, log: Logger) -> None: ...

class AouPackage:
    """
    Contains variables needed to request participant data.
    """

    def __init__(self, log: logging.Logger, config_file: str = "") -> None:
        self.aou_service_account: str = None
        self.awardee: str = None
        self.__config: ConfigParser = None
        self.data_directory: str = None
        self.endpoint: str = None
        self.__log: Logger = None
        self.pmi_account: str = None
        self.project: str = None
        self.token_file: str = None
    def inputs_complete(self) -> bool: ...
    def __input_ok(self, input_value: str) -> bool: ...
    def restore_aou_service_account(self) -> str: ...
    def restore_awardee(self) -> str: ...
    def restore_endpoint(self) -> str: ...
    def restore_pmi_account(self) -> str: ...
    def restore_project(self) -> str: ...
    def restore_token_file(self) -> str: ...
    def update_config(self) -> None: ...
