import logging
from configparser import ConfigParser
from logging import Logger

DUMMY: str = "<YourNameHere>"

def get_config(log: logging.Logger, config_file: str | None) -> ConfigParser: ...
def get_default_ini_path() -> str: ...
def make_config(config_file: str, log: Logger) -> None: ...

class AouPackage:
    """
    Contains variables needed to request participant data.
    """

    aou_service_account: str = None
    awardee: str = None
    __config: ConfigParser = None
    data_directory: str = None
    endpoint: str = None
    __log: Logger = None
    pmi_account: str = None
    project: str = None
    token_file: str = None

    def __init__(self, log: logging.Logger, config_file: str = "") -> None: ...
    def inputs_complete(self) -> bool: ...
    def __input_ok(self, input_value: str) -> bool: ...
    def restore_aou_service_account(self) -> str: ...
    def restore_awardee(self) -> str: ...
    def restore_endpoint(self) -> str: ...
    def restore_pmi_account(self) -> str: ...
    def restore_project(self) -> str: ...
    def restore_token_file(self) -> str: ...
    def update_config(self) -> None: ...
