import logging
from collections.abc import Callable

import wx

from src.getmyapidata.aou_package import AouPackage
from src.getmyapidata.gcloud_tools import GCloudTools
from src.getmyapidata.insite_api import InSiteAPI

class ApiGui(wx.Dialog):
    __aou_account_text_ctrl: wx.TextCtrl = None
    __aou_package: AouPackage = None
    __api_mgr: InSiteAPI = None
    __awardee_text_ctrl: wx.TextCtrl = None
    __gcloud_mgr: GCloudTools = None
    __is_cancelled: bool = False
    __log: logging.Logger = None
    __my_grid: wx.GridBagSizer = None
    __my_panel: wx.Panel = None
    __project_text_ctrl: wx.TextCtrl = None
    __pmi_account_text_ctrl: wx.TextCtrl = None
    __token_file_text_ctrl: wx.TextCtrl = None

    __buttons_and_text_boxes: dict = None
    __text_boxes_and_buttons: dict = None

    __cancel_button: wx.Button = None
    __gauge: wx.Gauge = None
    __ok_button: wx.Button = None
    __status_text: wx.StaticText = None

    def __init__(self, log: logging.Logger) -> None: ...
    def __add_controls(
        self,
        row: int,
        label: str,
        default: str,
        text_changed_fn: Callable,
        restore_fn: Callable,
        help_txt: str,
    ) -> None: ...
    def __add_title(self, label: str) -> None: ...
    def __auth_report(self, progress: bool | int | str) -> None: ...
    def __data_report(self, progress: bool | int | str) -> None: ...
    def __enable_if_inputs_complete(self) -> None: ...
    def __get_data(self) -> None: ...
    def __get_destination_directory(self) -> str: ...
    def __on_aou_service_account_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_auth_completion(self) -> None: ...
    def __on_awardee_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_cancel_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_close(self) -> None: ...
    def __on_data_completion(self) -> None: ...
    def __on_ok_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_menu_select(self, event: wx.EVT_MENU) -> None: ...
    def __on_pmi_account_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_project_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_restore_aou_service_account_button_clicked(
        self, event: wx.EVT_BUTTON
    ) -> None: ...
    def __on_restore_awardee_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_restore_endpoint_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_restore_pmi_account_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_restore_project_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_show_menu(self, event: wx.EVT_MENU) -> None: ...
    def __on_endpoint_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __set_gauge(self, pct: int) -> None: ...
    def __set_status_bar(self, status: str) -> None: ...
