import logging
from collections.abc import Callable
from configparser import ConfigParser

import wx

from src.getmyapidata.aou_package import AouPackage

class ApiGui(wx.Dialog):
    def __init__(self) -> None:
        self.__aou_account_text_ctrl: wx.TextCtrl = None
        self.__aou_package: AouPackage = None
        self.__awardee_text_ctrl: wx.TextCtrl = None
        self.__log: logging.Logger = None
        self.__my_grid: wx.GridBagSizer = None
        self.__my_panel: wx.Panel = None
        self.__project_text_ctrl: wx.TextCtrl = None
        self.__pmi_account_text_ctrl: wx.TextCtrl = None
        self.__token_file_text_ctrl: wx.TextCtrl = None

        self.__buttons_and_text_boxes: dict = {}
        self.__text_boxes_and_buttons: dict = {}

        self.__gauge: wx.Gauge = None
        self.__ok_button: wx.Button = None
        self.__status_text: wx.StaticText = None
    def __add_controls(
        self,
        row: int,
        label: str,
        default: str,
        text_changed_fn: Callable,
        restore_fn: Callable,
    ) -> None: ...
    def __add_title(self, label: str) -> None: ...
    def __enable_if_inputs_complete(self) -> None: ...
    def __get_data(self) -> None: ...
    def __get_destination_directory(self) -> str: ...
    def __on_aou_service_account_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_awardee_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_cancel_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_ok_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_menu_select(self, event: wx.EVT_MENU) -> None: ...
    def __on_pmi_account_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_project_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __on_restore_aou_service_account_button_clicked(
        self, event: wx.EVT_BUTTON
    ) -> None: ...
    def __on_restore_awardee_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_restore_pmi_account_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_restore_project_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_restore_token_file_button_clicked(self, event: wx.EVT_BUTTON) -> None: ...
    def __on_show_menu(self, event: wx.EVT_MENU) -> None: ...
    def __on_token_file_text_changed(self, event: wx.EVT_TEXT) -> None: ...
    def __set_progress(self, pct: int) -> None: ...
    def __set_status(self, text: str) -> None: ...
