import argparse
import configparser
import logging
from collections.abc import Callable as Callable

DUMMY: str = "<YourNameHere>"

def ensure_path_exists(filename: str, log: logging.Logger) -> bool: ...
def get_args(local_args: Callable) -> argparse.Namespace: ...
def get_base_path() -> str: ...
def get_config(
    args: argparse.Namespace, log: logging.Logger
) -> configparser.ConfigParser: ...
def get_default_ini_path() -> str: ...
def get_exe_path(log: logging.Logger) -> str: ...
def get_exe_version(log: logging.Logger) -> str: ...
def make_config(config_file: str) -> None: ...
def parse_version_file() -> str: ...
def resource_path(relative_path: str) -> str: ...
def update_config(config: configparser.ConfigParser) -> None: ...
