import logging
from collections.abc import Callable as Callable

def ensure_path_possible(filename: str, log: logging.Logger) -> bool: ...
def get_base_path() -> str: ...
def get_exe_path(log: logging.Logger) -> str: ...
def get_exe_version(log: logging.Logger) -> str: ...
def get_logging_directory(suggested_dir: str) -> str | None: ...
def get_temp_directory() -> str | None: ...
def is_writable(pat_to_test: str) -> bool: ...
def parse_version_file() -> str: ...
def resource_path(relative_path: str) -> str: ...
