import logging
import threading
from collections.abc import Callable as Callable

from src.getmyapidata.aou_package import AouPackage

def gcloud_tools_installed() -> bool: ...
def getoutput(command: str) -> list[str]: ...
def system(command: str) -> None: ...

class GCloudTools(threading.Thread):
    def __init__(
        self,
        aou_package: AouPackage,
        log: logging.Logger,
        status_fn: Callable = ...,
    ) -> None:
        self.__log: logging.Logger = None
        self.__aou_package: AouPackage = None
        self.__status_fn: Callable = None
    def __activate(self) -> None: ...
    def __auth(self) -> None: ...
    def __create_key_file(self) -> None: ...
    def get_token(self) -> str: ...
    def __report_error(self, status: str) -> None: ...
    def run(self) -> None: ...
