class Progress:
    def __init__(self):
        self.__num_to_do: int = None
        self.__num_complete: int = None
        self.__set: bool = False
    def increment(self, num_performed: int) -> None: ...
    def is_set(self) -> bool: ...
    def num_complete(self) -> int: ...
    def percent_complete(self) -> int: ...
    def set(self, num_to_do: int) -> None: ...
