class Progress:
    __num_to_do: int = None
    __num_complete: int = None
    __set: bool = False

    def __init__(self): ...
    def increment(self, num_performed: int) -> None: ...
    def is_set(self) -> bool: ...
    def num_complete(self) -> int: ...
    def percent_complete(self) -> int: ...
    def set(self, num_to_do: int) -> None: ...
