import logging
from configparser import ConfigParser

import wx

from paired_organizations import PairedOrganizations

class ApiGui(wx.Dialog):
    def __init__(self, config: ConfigParser) -> None:
        self.__config: ConfigParser = None
        self.__log: logging.Logger = None
        self.__project: str = None
        self.__pmi_account: str = None
        self.__aou_service_account: str = None
        self.__token_file: str = None

        self.__aou_service_account_text: wx.TextCtrl = None
        self.__gauge: wx.Gauge = None
        self.__ok_button: wx.Button = None
        self.__pmi_account_text: wx.TextCtrl = None
        self.__project_text: wx.TextCtrl = None
        self.__restore_aou_service_account_button: wx.Button = None
        self.__restore_pmi_account_button: wx.Button = None
        self.__restore_project_button: wx.Button = None
        self.__restore_token_file_button: wx.Button = None
        self.__status_text: wx.StaticText = None
        self.__token_file_text: wx.TextCtrl = None
    def __enable_if_inputs_complete(self) -> None: ...
    def __get_data(self) -> None: ...
    def __get_destination_directory(self) -> str: ...
    def __get_paired_organizations(self) -> PairedOrganizations: ...
    def __on_aou_service_account_text_changed(self, event: wx.Event) -> None: ...
    def __on_cancel_clicked(self, event: wx.Event) -> None: ...
    def __on_ok_clicked(self, event: wx.Event) -> None: ...
    def __on_pmi_account_text_changed(self, event: wx.Event) -> None: ...
    def __on_project_text_changed(self, event: wx.Event) -> None: ...
    def __on_restore_aou_service_account_button_clicked(
        self, event: wx.Event
    ) -> None: ...
    def __on_restore_pmi_account_button_clicked(self, event: wx.Event) -> None: ...
    def __on_restore_project_button_clicked(self, event: wx.Event) -> None: ...
    def __on_restore_token_file_button_clicked(self, event: wx.Event) -> None: ...
    def __on_token_file_text_changed(self, event: wx.Event) -> None: ...
    def __set_progress(self, pct: int) -> None: ...
    def __set_status(self, text: str) -> None: ...
