import argparse
import configparser
from collections.abc import Callable as Callable

def get_args(local_args: Callable) -> argparse.Namespace: ...
def get_config(args: argparse.Namespace) -> tuple[str, configparser.ConfigParser]: ...
def get_default_ini_path() -> str: ...
def make_config(config_file: str) -> None: ...
def update_config(config: configparser.ConfigParser) -> None: ...
